### ISSUE TITLE
无限正在保存或者连接失败

### ISSUE THREAD

**Issue by WanKa-zone** [LightAPIs/netease_aum#1]
尝试安装插件， 一直失败
或无限加载
![image](https://user-images.githubusercontent.com/45703375/183268800-e65b58ae-c9a9-4080-a773-3533ae0c97f3.png)
或连接失败
![image](https://user-images.githubusercontent.com/45703375/183268807-5557f032-fa2b-4de9-a5e1-5bcc4d6c4efc.png)

**Comment by LightAPIs** [comment]
在群晖社区里这个帖子([Failed Upload Connection to Audio Station when Adding Lyrics Plugin](https://community.synology.com/enu/forum/69/post/152974))也有提到过这个问题，在 DSM 7.1-42661 中的 Audio Station(7.0.1-5209) 会无法安装插件，有人回帖说官方有给出 7.0.1-5210 版本的套件处理该问题，不过我在官网上搜索 DSM 7.1 最新 Audio Station 套件版本只有 7.0.1-5209，所以可能是他们的客服或技术人员单独分发的。
